# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"

  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'


  # Button 1 is a switch (some devcies show up as switches some as lights make sure you use the corresponding file)
  button_1_name: "Button 2"
  button_1_id: couch_lamp
  button_1_icon: $lightbulb
  button_1_device: "switch.athom_smart_plug_v3_50ebc0_switch"

esphome:
  name: enphdisp
  friendly_name: Enphase info display
  comment: "lilygo tdisplays3 170px * 320px Smart Screen"  
    
packages:
  # Generic configuration for ESP32 screens
  base: !include modules/common/base.yaml
  globals: !include modules/common/globals.yaml
  wifi: !include modules/common/wifi.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml
  images: !include modules/common/images.yaml
  
  # Harware description file
  hardware: !include modules/hardware/lilygo-tdisplays3.yaml
  
  # Base settings for LVGL libary
  lvgl_time: !include modules/lvgl/base/lvgl_time_sntp.yaml
  lvgl_sensors: !include modules/lvgl/base/lvgl_sensors_base.yaml
  lvgl_base: !include modules/lvgl/base/lvgl_base_no_touchscreen.yaml
  
  # Update button and relay state from Home Assistant
  button_1_sensor: !include { file: modules/sensors/basic_switch_or_light_button_state.yaml, vars: { id: 1 } } 
 

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  theme: !include { file: modules/lvgl/base/lvgl_theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include { file: modules/lvgl/screens/boot_screen.yaml, vars: { height: $screen_height, width: $screen_width  } }

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      bg_color: black
      bg_opa: cover
      pad_all: 5
      widgets: # Include all the buttons
        - button: !include { file: modules/lvgl/buttons/basic_switch_button.yaml, vars: { id: 1, height: $button_height_single } }

